// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTtjEN24HL0wIFHL0-zHtPPNssb8two6Y',
    appId: '1:507287568722:android:cefbacb2b43725383dfa8b',
    messagingSenderId: '507287568722',
    projectId: 'application-mobile-mvst',
    databaseURL: 'https://application-mobile-mvst-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'application-mobile-mvst.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGIdevmYkbBzPJ7ozu1t0r0EROKjb5TA0',
    appId: '1:507287568722:ios:c30916385d6b341c3dfa8b',
    messagingSenderId: '507287568722',
    projectId: 'application-mobile-mvst',
    databaseURL: 'https://application-mobile-mvst-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'application-mobile-mvst.appspot.com',
    iosBundleId: 'com.app.mvst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx2m1b7Z9bZFRJUMCgn1xYX_vTmfLmtgE',
    appId: '1:507287568722:web:40572afe6bb232c93dfa8b',
    messagingSenderId: '507287568722',
    projectId: 'application-mobile-mvst',
    authDomain: 'application-mobile-mvst.firebaseapp.com',
    databaseURL: 'https://application-mobile-mvst-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'application-mobile-mvst.appspot.com',
    measurementId: 'G-301QVFXQ9V',
  );

}